# JuliaFormatter.jl configuration file
# Run `using JuliaFormatter; format(".")` to apply formatting

indent = 4
margin = 92
always_for_in = true
always_use_return = true
remove_extra_newlines = true
separate_kwargs_with_semicolon = true
short_to_long_function_def = true
