name = "Discreet"
uuid = "c2843242-4f35-58a6-a2a0-7e7527607317"
version = "0.3.3"
authors = ["cynddl"]
license = "MIT"
description = "A Julia package for estimating entropy and mutual information from discrete samples with bias correction"
homepage = "https://github.com/cynddl/Discreet.jl"
repository = "https://github.com/cynddl/Discreet.jl"
keywords = ["entropy", "mutual-information", "information-theory", "statistics", "bias-correction"]
categories = ["Math", "Statistics"]

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.33, 0.34"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]